# Generated by Django 5.1.3 on 2024-12-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Jokes",
            new_name="Joke",
        ),
    ]
